const state={type:'stay',guests:2,base:295,baseName:'Classic room & spa',extras:[]};
const drawer=document.querySelector('.drawer'),scrim=document.querySelector('.scrim'),sections=[...document.querySelectorAll('.drawer-body section')],steps=[...document.querySelectorAll('.steps span')];let step=0;
const plans={stay:[['Classic room & spa',295,'One night · breakfast · spa access'],['Woodland suite',395,'One night · breakfast · spa access'],['Two-night retreat',620,'Two nights · breakfast · spa access']],day:[['Morning spa',99,'8:30am–2:00pm · lunch included'],['Twilight spa',89,'3:30pm–9:00pm · dinner included'],['Complete spa day',139,'Full day · lunch included']]};
function renderPlans(){const box=document.querySelector('#baseOptions');box.innerHTML=plans[state.type].map((p,i)=>`<button class="${i?'':'active'}" data-plan="${i}"><strong>${p[0]} <em>£${p[1]} pp</em></strong><small>${p[2]}</small></button>`).join('');const p=plans[state.type][0];state.baseName=p[0];state.base=p[1];box.querySelectorAll('button').forEach(b=>b.onclick=()=>{box.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const p=plans[state.type][+b.dataset.plan];state.baseName=p[0];state.base=p[1];update()});update()}
function update(){const subtotal=state.base*state.guests+state.extras.reduce((s,x)=>s+x.price*x.qty,0),discount=state.extras.length?Math.round(subtotal*.08):0;document.querySelector('#total').textContent=`£${subtotal-discount}`;document.querySelector('#saving').textContent=`Package saving £${discount}`;document.querySelector('#basketItems').textContent=`${state.guests} guest${state.guests>1?'s':''} · ${state.baseName}`;document.querySelector('#review').innerHTML=`<div class="extras-item"><span>${state.baseName} × ${state.guests}</span><strong>£${state.base*state.guests}</strong></div>${state.extras.map(x=>`<div class="extras-item"><span>${x.name} × ${x.qty}</span><strong>£${x.price*x.qty}</strong></div>`).join('')}<div class="extras-item"><span>Package saving</span><strong>−£${discount}</strong></div>`}
function open(){drawer.classList.add('open');scrim.classList.add('open');drawer.setAttribute('aria-hidden','false')}function close(){drawer.classList.remove('open');scrim.classList.remove('open');drawer.setAttribute('aria-hidden','true')}
document.querySelectorAll('.book-open').forEach(b=>b.onclick=open);document.querySelector('.close').onclick=close;scrim.onclick=close;
document.querySelectorAll('.choice button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.type=b.dataset.type;renderPlans()});
document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{state.guests=Math.max(1,Math.min(8,state.guests+(b.dataset.count==='+'?1:-1)));document.querySelector('#guests').textContent=state.guests;update()});
const treatmentData=[['Grounding full-body massage',95],['Radiance facial',89],['Woodland head & shoulder ritual',65],['Champagne on arrival',45]];document.querySelector('#extras').innerHTML=treatmentData.map((x,i)=>`<div class="extras-item"><span>${x[0]}<small> · £${x[1]} pp</small></span><button data-extra="${i}">Add +</button></div>`).join('');document.querySelectorAll('[data-extra]').forEach(b=>b.onclick=()=>{const x=treatmentData[+b.dataset.extra],found=state.extras.find(e=>e.name===x[0]);if(found)found.qty++;else state.extras.push({name:x[0],price:x[1],qty:1});b.textContent='Added ✓';update()});
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const found=state.extras.find(e=>e.name===b.dataset.add);if(!found)state.extras.push({name:b.dataset.add,price:+b.dataset.price,qty:1});open();go(1);update()});
function go(n){step=n;sections.forEach((s,i)=>s.classList.toggle('active',i===n));steps.forEach((s,i)=>s.classList.toggle('active',i===n))}document.querySelectorAll('.next').forEach((b,i)=>b.onclick=()=>go(i+1));
const today=new Date();today.setDate(today.getDate()+1);document.querySelector('#arrival').value=today.toISOString().slice(0,10);today.setDate(today.getDate()+1);document.querySelector('#departure').value=today.toISOString().slice(0,10);
document.querySelector('#confirm').onclick=()=>{document.querySelector('#confirm').textContent='Request received ✓';document.querySelector('#confirm').disabled=true};renderPlans();
