const treatments=[
 {id:'grounding',name:'Grounding full-body massage',category:'massage',minutes:60,price:95,description:'A tailored, full-body treatment with pressure chosen for you.'},
 {id:'deep',name:'Deep muscle release',category:'massage',minutes:60,price:105,description:'Focused work to ease areas carrying the most tension.'},
 {id:'radiance',name:'Radiance facial',category:'face',minutes:60,price:89,description:'Cleanse, nourish and restore luminosity.'},
 {id:'proage',name:'Pro-ageing facial ritual',category:'face',minutes:75,price:115,description:'A considered facial with massage and intensive hydration.'},
 {id:'cocoon',name:'Woodland body cocoon',category:'body',minutes:75,price:119,description:'Exfoliation, wrap and scalp massage for complete reset.'},
 {id:'head',name:'Head & shoulder ritual',category:'body',minutes:45,price:65,description:'Slow, focused release for the scalp, neck and shoulders.'}
];
const venues=[
 {id:'bertrams',name:"Bertram's",note:'Season-led dining',description:'The occasion restaurant: confident Lancashire cooking and a table worth dressing for.',price:0},
 {id:'spa-lunch',name:'Spa lunch',note:'Relaxed daytime dining',description:'A robe-friendly lunch worked naturally into a full spa day.',price:32},
 {id:'afternoon-tea',name:'Afternoon tea',note:'A slow afternoon',description:'Savouries, warm scones and small sweets with tea or coffee.',price:38}
];
const menus={
 bertrams:[['To begin',[['Lancashire cheese & garden leek','malted grain · chive','£12'],['Market fish','coastal herbs · cultured cream','£16']]],['Main plates',[['Lake District beef','onion · smoked potato · roasting juices','£32'],['Day-boat fish','shellfish sauce · seasonal greens','£29'],['Woodland vegetables','barley · aged cheese · herbs','£24']]],['To finish',[['Dark chocolate','malted milk · caramel','£11'],['Lancashire cheese','fruit bread · orchard chutney','£14']]]],
 'spa-lunch':[['Lunch',[['Soup of the day','artisan bread','Included'],['Seasonal grain bowl','roasted vegetables · herbs','Included'],['Grilled chicken salad','leaves · seeds · house dressing','Included']]]],
 'afternoon-tea':[['Afternoon tea',[['The savouries','chef’s seasonal selection','Included'],['Warm scones','preserves · clotted cream','Included'],['The sweets','a changing collection of patisserie','Included']]]]
};
const plans={stay:[['Classic room & spa',295,'One night · breakfast · spa access'],['Feature room retreat',395,'One night · breakfast · spa access'],['Two-night reset',620,'Two nights · breakfast · spa access']],day:[['Morning spa',99,'8:30–14:00 · lunch included'],['Twilight spa',89,'15:30–21:00 · dinner included'],['Complete spa day',139,'Full day · lunch included']]};
const state={type:'stay',baseName:'Classic room & spa',base:295,guests:[{name:'Guest 1',type:'Adult'},{name:'Guest 2',type:'Adult'}],selections:{},venue:'bertrams',step:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function renderTreatmentCards(filter='all'){const list=filter==='all'?treatments:treatments.filter(t=>t.category===filter);$('#treatmentCards').innerHTML=list.map(t=>`<article><div><h3>${t.name}</h3><small>${t.minutes} minutes · ${t.description}</small></div><span>£${t.price}</span><button data-quick="${t.id}">Add +</button></article>`).join('');$$('[data-quick]').forEach(b=>b.onclick=()=>{openDrawer();go(2);const first=state.guests[0];state.selections[0]={treatment:b.dataset.quick,time:'11:00'};renderGuestTreatments();update()})}
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTreatmentCards(b.dataset.filter)});
function renderVenues(){const html=venues.map((v,i)=>`<button class="${i?'':'active'}" data-venue-preview="${v.id}"><span>${v.note}</span><h3>${v.name}</h3><p>${v.description}</p><b>See sample menu →</b></button>`).join('');$('#venues').innerHTML=html;$$('[data-venue-preview]').forEach(b=>b.onclick=()=>{$$('[data-venue-preview]').forEach(x=>x.classList.toggle('active',x===b));renderMenu(b.dataset.venue);$('#menuList').scrollIntoView({behavior:'smooth'})})}
function renderMenu(id='bertrams'){$('#menuList').innerHTML=menus[id].map(g=>`<div class="menu-group"><h3>${g[0]}</h3>${g[1].map(d=>`<div class="dish"><div><strong>${d[0]}</strong><small>${d[1]}</small></div><span>${d[2]}</span></div>`).join('')}</div>`).join('')}
const drawer=$('.drawer'),scrim=$('.scrim'),sections=$$('.drawer-body section'),stepButtons=$$('.steps button');
function openDrawer(){drawer.classList.add('open');scrim.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeDrawer(){drawer.classList.remove('open');scrim.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.style.overflow=''}
$$('.book-open').forEach(b=>b.onclick=openDrawer);$('.close').onclick=closeDrawer;scrim.onclick=closeDrawer;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});
function go(n){state.step=n;sections.forEach((s,i)=>s.classList.toggle('active',i===n));stepButtons.forEach((s,i)=>s.classList.toggle('active',i===n));if(n===2)renderGuestTreatments();if(n===3)renderDiningOptions();if(n===4)update();drawer.querySelector('.drawer-body').scrollTop=0}
$$('.next').forEach((b,i)=>b.onclick=()=>go(i+1));stepButtons.forEach((b,i)=>b.onclick=()=>{if(i<=state.step)go(i)});
$$('.choice button').forEach(b=>b.onclick=()=>{$$('.choice button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.type=b.dataset.type;renderPlans()});
function renderPlans(){const box=$('#baseOptions');box.innerHTML=plans[state.type].map((p,i)=>`<button class="${i?'':'active'}" data-plan="${i}"><strong>${p[0]} <em>£${p[1]} pp</em></strong><small>${p[2]}</small></button>`).join('');selectPlan(0);$$('[data-plan]').forEach(b=>b.onclick=()=>{$$('[data-plan]').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectPlan(+b.dataset.plan)})}
function selectPlan(i){const p=plans[state.type][i];state.baseName=p[0];state.base=p[1];update()}
function renderGuests(){const list=$('#guestList');list.innerHTML=state.guests.map((g,i)=>`<div class="guest-card"><label>Guest ${i+1}<input value="${g.name}" data-guest-name="${i}" aria-label="Guest ${i+1} name"></label><label>Type<select data-guest-type="${i}"><option>Adult</option><option ${g.type==='Young adult'?'selected':''}>Young adult</option></select></label>${state.guests.length>1?`<button data-remove="${i}" aria-label="Remove guest ${i+1}">×</button>`:'<span></span>'}</div>`).join('');$$('[data-guest-name]').forEach(x=>x.oninput=()=>{state.guests[+x.dataset.guestName].name=x.value||`Guest ${+x.dataset.guestName+1}`;update()});$$('[data-guest-type]').forEach(x=>x.onchange=()=>state.guests[+x.dataset.guestType].type=x.value);$$('[data-remove]').forEach(x=>x.onclick=()=>{state.guests.splice(+x.dataset.remove,1);state.selections={};renderGuests();update()})}
$('.add-guest').onclick=()=>{if(state.guests.length<8){state.guests.push({name:`Guest ${state.guests.length+1}`,type:'Adult'});renderGuests();update()}};
function renderGuestTreatments(){$('#guestTreatments').innerHTML=state.guests.map((g,i)=>{const s=state.selections[i]||{treatment:'none',time:'11:00'};return `<div class="guest-treatment"><h3>${g.name||`Guest ${i+1}`}</h3><div class="fields"><label>Treatment<select data-treatment="${i}"><option value="none">Spa only · no treatment</option>${treatments.map(t=>`<option value="${t.id}" ${s.treatment===t.id?'selected':''}>${t.name} · ${t.minutes}m · £${t.price}</option>`).join('')}</select></label><label>Start time<select data-time="${i}" ${s.treatment==='none'?'disabled':''}>${['10:00','11:00','12:00','14:00','15:00','16:00'].map(t=>`<option ${s.time===t?'selected':''}>${t}</option>`).join('')}</select></label></div></div>`}).join('');$$('[data-treatment]').forEach(x=>x.onchange=()=>{const i=+x.dataset.treatment;state.selections[i]={treatment:x.value,time:state.selections[i]?.time||'11:00'};renderGuestTreatments();update()});$$('[data-time]').forEach(x=>x.onchange=()=>{state.selections[+x.dataset.time].time=x.value;update()})}
function renderDiningOptions(){$('#diningOptions').innerHTML=venues.map(v=>`<button class="dining-option ${state.venue===v.id?'active':''}" data-dining="${v.id}"><h3>${v.name}${v.price?` · £${v.price} pp`:''}</h3><small>${v.description}</small></button>`).join('');$$('[data-dining]').forEach(b=>b.onclick=()=>{state.venue=b.dataset.dining;renderDiningOptions();update()})}
function totals(){const base=state.base*state.guests.length,treatmentTotal=Object.values(state.selections).reduce((sum,s)=>sum+(treatments.find(t=>t.id===s.treatment)?.price||0),0),dining=(venues.find(v=>v.id===state.venue)?.price||0)*state.guests.length,subtotal=base+treatmentTotal+dining,eligible=treatmentTotal+dining,discount=eligible?Math.round(eligible*.1):0;return{base,treatmentTotal,dining,subtotal,discount,total:subtotal-discount}}
function update(){const x=totals();$('#total').textContent=`£${x.total}`;$('#saving').textContent=`Package saving £${x.discount}`;$('#basketItems').textContent=`${state.guests.length} guest${state.guests.length>1?'s':''} · ${state.baseName}`;const chosen=state.guests.map((g,i)=>{const s=state.selections[i],t=treatments.find(t=>t.id===s?.treatment);return `<div class="review-row"><span>${g.name}</span><strong>${t?`${t.name} · ${s.time}`:'Spa only'}</strong></div>`}).join('');$('#review').innerHTML=`<div class="review-block"><h3>${state.baseName}</h3><div class="review-row"><span>${state.guests.length} guests</span><strong>£${x.base}</strong></div></div><div class="review-block"><h3>Everybody's treatments</h3>${chosen}<div class="review-row"><span>Treatment total</span><strong>£${x.treatmentTotal}</strong></div></div><div class="review-block"><h3>${venues.find(v=>v.id===state.venue).name} · ${$('#diningTime')?.value||'19:00'}</h3><div class="review-row"><span>Dining allocation</span><strong>£${x.dining}</strong></div></div><div class="review-block"><div class="review-row"><span>Package saving (10% of extras)</span><strong>−£${x.discount}</strong></div><div class="review-row"><span>Total</span><strong>£${x.total}</strong></div></div>`}
$('#diningTime').onchange=update;$('#confirm').onclick=()=>{$('#confirm').textContent='Itinerary request received ✓';$('#confirm').disabled=true};
const today=new Date();today.setDate(today.getDate()+1);$('#arrival').value=today.toISOString().slice(0,10);today.setDate(today.getDate()+1);$('#departure').value=today.toISOString().slice(0,10);
renderTreatmentCards();renderVenues();renderMenu();renderPlans();renderGuests();update();
