const visitTypes=[['day','Spa day','A full day with unlimited thermal access'],['twilight','Twilight','Thermal access from 5.30–9.30pm'],['stay','Spa break','Thermal access, room and breakfast']];
const packages={day:[['Thermal Experience',120,'Unlimited thermal access all day'],['Thermal & Dine',152,'Thermal access, main, dessert & wine'],['TEMPLESPA Experience Day',225,'Dining and one 60-minute treatment'],['Signature Spa Day',289,'Dining and 105-minute Paradise Escape']],twilight:[['Twilight Experience',85,'5.30–9.30pm thermal access']],stay:[['Bed & Breakfast',200,'Room, breakfast & arrival-day spa'],['Dinner, Bed & Breakfast',240,'As B&B plus £40 dinner credit']]};
const venues=[['restaurant','Spa Restaurant','Main, dessert & wine','0'],['terrace','Tapas on the Terrace','Relaxed small plates by the firepit','22'],['rooftop','Rooftop Pizza','Stone-baked pizza with a view','20'],['none','No table, thank you','Keep the day open','0']];
const extras=[['rasul','Private Rasul Mud Ritual',45,'Mineral mud, steam and gentle rain for 2–4 guests'],['departure','Departure-day spa access',75,'Extend an overnight escape into the next day'],['cocktail','Prosecco cocktail',13,'A sparkling pause, per guest'],['suite','Suite upgrade',90,'More space and a sense of occasion, per room'],['bread','Breads & truffle aioli',7,'Something extra at the table, per party'],['late','Late checkout',45,'One last slow morning, per room']];
const state={type:'day',package:0,guests:[{name:'Guest 1'},{name:'Guest 2'}],treatments:{},venue:'restaurant',extras:new Set(),step:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const gbp=n=>'£'+Math.round(n).toLocaleString();
function weekdayFactor(){let d=new Date($('#date').value+'T12:00:00').getDay();return d===6?40:(d===5||d===0)?30:0}
function drawTypes(){$('#types').innerHTML=visitTypes.map(v=>`<button class="choice ${state.type===v[0]?'active':''}" data-type="${v[0]}"><strong>${v[1]}</strong><small>${v[2]}</small></button>`).join('');$$('[data-type]').forEach(b=>b.onclick=()=>{state.type=b.dataset.type;state.package=0;drawTypes();drawPackages();$('#departureLabel').style.display=state.type==='stay'?'block':'none';update()})}
function drawPackages(){let uplift=weekdayFactor();$('#packages').innerHTML=packages[state.type].map((p,i)=>{let price=p[1]+(state.type==='day'?uplift:state.type==='twilight'?Math.round(uplift/3):uplift);return`<button class="choice ${state.package===i?'active':''}" data-package="${i}"><strong>${p[0]} · ${gbp(price)}pp</strong><small>${p[2]}</small></button>`}).join('');$$('[data-package]').forEach(b=>b.onclick=()=>{state.package=+b.dataset.package;drawPackages();update()})}
function drawGuests(){$('#guests').innerHTML=state.guests.map((g,i)=>`<div class="guest"><label>Guest ${i+1}<input data-name="${i}" value="${g.name}"></label><label>Age group<select><option>Adult</option><option>Young adult</option></select></label>${state.guests.length>1?`<button class="choice" data-remove="${i}">Remove</button>`:''}</div>`).join('');$$('[data-name]').forEach(x=>x.oninput=()=>{state.guests[+x.dataset.name].name=x.value||`Guest ${+x.dataset.name+1}`;update()});$$('[data-remove]').forEach(x=>x.onclick=()=>{state.guests.splice(+x.dataset.remove,1);state.treatments={};drawGuests();update()})}
$('#addGuest').onclick=()=>{if(state.guests.length<8){state.guests.push({name:`Guest ${state.guests.length+1}`});drawGuests();update()}};
function drawTreatments(){let opts=TREATMENTS.map(t=>`<option value="${t.id}">${t.name} · ${t.min}m · £${t.price}</option>`).join('');$('#guestTreatments').innerHTML=state.guests.map((g,i)=>{let s=state.treatments[i]||{id:'none',time:'11:00'};return`<div class="guest-treatment"><h3>${g.name}</h3><div class="form-grid"><label>Treatment<select data-treatment="${i}"><option value="none">Spa only · no treatment</option>${opts}</select></label><label>Preferred start<select data-time="${i}">${['10:00','11:00','12:00','14:00','15:00','16:00','17:00'].map(x=>`<option ${x===s.time?'selected':''}>${x}</option>`).join('')}</select></label></div></div>`}).join('');$$('[data-treatment]').forEach(x=>{x.value=state.treatments[+x.dataset.treatment]?.id||'none';x.onchange=()=>{let i=+x.dataset.treatment;state.treatments[i]={id:x.value,time:state.treatments[i]?.time||'11:00'};update()}});$$('[data-time]').forEach(x=>x.onchange=()=>{let i=+x.dataset.time;state.treatments[i]={id:state.treatments[i]?.id||'none',time:x.value};update()})}
function drawDining(){$('#diningChoices').innerHTML=venues.map(v=>`<button class="choice ${state.venue===v[0]?'active':''}" data-venue="${v[0]}"><strong>${v[1]}${+v[3]?' · £'+v[3]+'pp':''}</strong><small>${v[2]}</small></button>`).join('');$$('[data-venue]').forEach(b=>b.onclick=()=>{state.venue=b.dataset.venue;drawDining();update()})}
function drawExtras(){$('#extras').innerHTML=extras.filter(x=>x[0]!=='departure'||state.type==='stay').map(x=>`<button class="choice ${state.extras.has(x[0])?'active':''}" data-extra="${x[0]}"><strong>${x[1]} · £${x[2]}</strong><small>${x[3]}</small></button>`).join('');$$('[data-extra]').forEach(b=>b.onclick=()=>{state.extras.has(b.dataset.extra)?state.extras.delete(b.dataset.extra):state.extras.add(b.dataset.extra);drawExtras();update()})}
function calc(){let p=packages[state.type][state.package],uplift=weekdayFactor(),pp=p[1]+(state.type==='day'?uplift:state.type==='twilight'?Math.round(uplift/3):uplift),base=pp*state.guests.length,treat=Object.values(state.treatments).reduce((a,s)=>a+(TREATMENTS.find(t=>t.id===s.id)?.price||0),0),v=venues.find(v=>v[0]===state.venue),dining=+v[3]*state.guests.length,extra=[...state.extras].reduce((a,id)=>{let x=extras.find(e=>e[0]===id);return a+x[2]*(['cocktail'].includes(id)?state.guests.length:1)},0),count=Object.values(state.treatments).filter(x=>x.id!=='none').length+state.extras.size+(state.venue!=='none'&&dining>0?1:0),rate=count>=6?.15:count>=4?.10:count>=2?.05:0,discount=Math.round((treat+dining+extra)*rate);return{p,pp,base,treat,v,dining,extra,count,rate,discount,total:base+treat+dining+extra-discount}}
function update(){let x=calc();$('#basket').innerHTML=`<p class="eyebrow">Your package</p><h3>${x.p[0]}</h3><div class="basket-row"><span>${state.guests.length} guests</span><b>${gbp(x.base)}</b></div><div class="basket-row"><span>Treatments</span><b>${gbp(x.treat)}</b></div><div class="basket-row"><span>Dining & extras</span><b>${gbp(x.dining+x.extra)}</b></div><div class="saving"><strong>${x.rate?x.rate*100+'% saving unlocked':'Add 2 extras to save 5%'}</strong><br>${x.rate?'You save '+gbp(x.discount):'Your saving grows to 15%'}</div><small>Estimated total</small><div class="total">${gbp(x.total)}</div><p><small>Live availability and final pricing confirmed after request.</small></p>`;$('#mobileTotal').textContent=`Estimated total ${gbp(x.total)} · Saving ${gbp(x.discount)}`;drawReview(x)}
function drawReview(x){if(!$('#review'))return;let ts=state.guests.map((g,i)=>{let s=state.treatments[i],t=TREATMENTS.find(t=>t.id===s?.id);return`<div class="review-card"><strong>${g.name}</strong><br>${t?t.name+' · '+t.min+' mins at '+s.time:'Thermal experience only'}</div>`}).join('');$('#review').innerHTML=`<div class="review-card"><strong>${x.p[0]}</strong><br>${state.guests.length} guests · ${$('#date').value} · ${gbp(x.base)}</div>${ts}<div class="review-card"><strong>${x.v[1]}</strong><br>${state.venue==='none'?'No reservation':$('#diningTime').value+' · '+($('#dietary').value||'No dietary notes')}</div><div class="review-card"><strong>Finishing touches</strong><br>${[...state.extras].map(id=>extras.find(e=>e[0]===id)[1]).join(', ')||'None selected'}</div><div class="review-card"><strong>Package saving ${gbp(x.discount)}</strong><br>Estimated total ${gbp(x.total)}</div>`}
function go(n){state.step=n;$$('.step').forEach((x,i)=>x.classList.toggle('active',i===n));drawProgress();if(n===2)drawTreatments();if(n===3)drawDining();if(n===4)drawExtras();update();scrollTo({top:180,behavior:'smooth'})}function drawProgress(){progress.innerHTML=['Visit','Party','Treat','Dine','Extras','Review'].map((x,i)=>`<button data-num="0${i+1}" class="${i===state.step?'active':''}" data-step="${i}">${i+1} · ${x}</button>`).join('');$$('[data-step]').forEach(b=>b.onclick=()=>{if(+b.dataset.step<=state.step)go(+b.dataset.step)})}
$$('.next').forEach((b,i)=>b.onclick=()=>go(i+1));$('#diningTime').onchange=update;$('#dietary').oninput=update;$('#date').onchange=()=>{drawPackages();update()};$('#confirm').onclick=()=>{if(!$('#lead').value||!$('#email').value){alert('Please add the lead guest and email.');return}$('#confirm').textContent='Itinerary request received ✓';$('#confirm').disabled=true};let d=new Date();d.setDate(d.getDate()+7);$('#date').value=d.toISOString().slice(0,10);d.setDate(d.getDate()+1);$('#departure').value=d.toISOString().slice(0,10);let q=new URLSearchParams(location.search).get('treatment');if(q&&TREATMENTS.some(t=>t.id===q))state.treatments[0]={id:q,time:'11:00'};drawProgress();drawTypes();drawPackages();drawGuests();update();
